.PHONY: clean All

All:
	@echo "----------Building project:[ Operator_overloadibng - Debug ]----------"
	@cd "Operator_overloadibng" && "$(MAKE)" -f  "Operator_overloadibng.mk"
clean:
	@echo "----------Cleaning project:[ Operator_overloadibng - Debug ]----------"
	@cd "Operator_overloadibng" && "$(MAKE)" -f  "Operator_overloadibng.mk" clean
