.PHONY: clean All

All:
	@echo "----------Building project:[ Newone - Debug ]----------"
	@cd "Newone" && "$(MAKE)" -f  "Newone.mk"
clean:
	@echo "----------Cleaning project:[ Newone - Debug ]----------"
	@cd "Newone" && "$(MAKE)" -f  "Newone.mk" clean
