.PHONY: clean All

All:
	@echo "----------Building project:[ fuction_scope_rules - Debug ]----------"
	@cd "username2" && "$(MAKE)" -f  "fuction_scope_rules.mk"
clean:
	@echo "----------Cleaning project:[ fuction_scope_rules - Debug ]----------"
	@cd "username2" && "$(MAKE)" -f  "fuction_scope_rules.mk" clean
