.PHONY: clean All

All:
	@echo "----------Building project:[ accenture - Debug ]----------"
	@cd "accenture" && "$(MAKE)" -f  "accenture.mk"
clean:
	@echo "----------Cleaning project:[ accenture - Debug ]----------"
	@cd "accenture" && "$(MAKE)" -f  "accenture.mk" clean
